import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "@/sass/app.scss";
import logo from "./logo.svg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s — Jake Ord",
    default: "Jake Ord — Interaction Designer"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistSans.variable}>
        <a className="ob-skip-link" href="#main-content">
          Skip to main content
        </a>
        <div className="ob-container">
          <header className="ob-header ob-cluster">
            <Image src={logo} alt="" width="40" height="50" aria-hidden="true" />
            <Link href="/" className="ob-logo">
              Jake Ord <br />
              <span>Interaction Designer</span>
            </Link>
          </header>
          <main id="main-content">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
